name: jaspr_material_design_components
description: Material Design Components para Jaspr. Integra los componentes de Material Web Components usando el CDN para encapsular y proporcionar sus elementos.
version: 25.4.5+31
repository: https://github.com/neoacevedo/jaspr_material_design_components.git

topics:
  - jaspr
  - web
  - html
  - material
  - css

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  jaspr: ">=0.19.0 <0.20.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
