name: jaspr_material_design_components
description: Material Design Components para Jaspr.
version: 25.04.05+30
repository: https://github.com/neoacevedo/jaspr_material_design_components.git

environment:
  sdk: ^3.7.2

dependencies:
  jaspr: ^0.18.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
